services:
  postgres:
    container_name: poke-db
    image: postgres:16
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres:/data/postgres
    restart: unless-stopped
    ports:
      - ${DATABASE_PORT}:5432

volumes:
  postgres:
